[server]
headless = true
address = "0.0.0.0"
port = 5000
maxUploadSize = 5000
maxMessageSize = 5000
fileWatcherType = "none"
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
